version: '3.7'
services:
  redis:
    image: redis:latest
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  bot:
    build: .
    command: python bot.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis